name: Flutter Build and Upload Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: microsoft

      - name: Install yq
        uses: mikefarah/yq@v4.42.1

      - name: Get pubspec version
        id: get_flutter_app_version
        run: |
          VERSION=$(yq e .version pubspec.yaml | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          echo "TAG_VERSION=$VERSION" >> $GITHUB_ENV
      
      
      - name: Check if git tag exists and increment version if necessary
        run: |
          TAG_VERSION=${{ env.TAG_VERSION }}
          TAG_EXISTS=$(git ls-remote --tags origin refs/tags/v$TAG_VERSION)
          while [[ "$TAG_EXISTS" != "" ]]; do
            VERSION_ARRAY=(${TAG_VERSION//./ })
            VERSION_ARRAY[2]=$((${VERSION_ARRAY[2]}+1))
            NEW_VERSION="${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}.${VERSION_ARRAY[2]}"
            TAG_EXISTS=$(git ls-remote --tags origin refs/tags/v$NEW_VERSION)
          done
          echo "NEW_TAG_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$NEW_VERSION"
      
      - name: Create git tag
        run: |
          git tag "v${{ env.NEW_TAG_VERSION }}"
          git push origin "v${{ env.NEW_TAG_VERSION }}"
      


      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Build an AppBundle
        run: flutter build appbundle --release

      - name: Save APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk

      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-appbundle
          path: build/app/outputs/bundle/release/*.aab

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/*.aab,build/app/outputs/flutter-apk/*.apk"
          tag: "v${{ steps.check_and_increment_tag.outputs.version }}"
